services:
  scion1-1:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion1-2:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion1-3:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion1-4:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion1-5:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion1-6:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion1-7:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-1:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-2:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-3:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-4:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-5:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-6:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-7:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-8:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-9:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-10:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-11:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-12:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-13:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-14:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-15:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-16:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-17:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-18:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-19:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-20:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-21:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-22:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-23:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-24:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-25:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-26:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-27:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-28:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion3-1:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion3-2:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion3-3:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
