services:
  scion11:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion12:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion13:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion14:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion15:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion21:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion22:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion23:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion24:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion25:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion31:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion32:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion33:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion34:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion35:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
