services:
  scion1-1:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion1-2:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion1-3:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion1-4:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion1-5:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-1:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-2:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-3:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-4:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion2-5:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion3-1:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion3-2:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion3-3:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion3-4:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion3-5:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion4-1:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion4-2:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion4-3:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion4-4:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
  scion4-5:
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /Users/Shared:/shared
