name: Running Docker Image on MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Docker
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          while ! docker system info > /dev/null 2>&1; do sleep 1; done
      - name: Install Docker Compose v1
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: make up