name: Running Docker Image on MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Docker
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          while ! docker system info > /dev/null 2>&1; do sleep 1; done
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: make up