name: Run integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Start containers & Install dependencies
      run: make up

    - name: Wait for containers to start0
      run: sleep 10

    - name: Run tests
      run: make test